### PR TITLE
LICENSE info added

### PR DESCRIPTION
**Pull request by reverendus**

### CODE REVIEW

**Comment by reverendus** [comment]
Regarding #1

**Comment by reverendus** [comment]
`COPYING` has been already added to the root directory in a different commit

**Comment by rainbreak** [comment]
We can't use `MakerDAO` as a copyright holder as it doesn't exist in any formal sense. Instead, use names of individual contributors - so just switch out `MakerDao` for yourself.

**Comment by reverendus** [comment]
That's what I wanted to verify. Changed it to my name then.

**Comment by reverendus** [comment]
Feel free to add yours afterwards of course

**Pull request merged**
